### PR TITLE
added json parsing for sqs message body

### PR DESCRIPTION
**Pull request by jegesh**
When trying to use the sqs sensor, I kept seeing messages pulled from the queue, but nothing detectable happening in stackstorm.  Then I found this in the sensor logs:

```
2019-05-29 14:07:17,443 140124228289552 WARNING trigger_dispatcher [-] Failed to validate payload ({'queue': u'myqueue', 'body': '{"params": { "target": "dedacted","stack_id": "test-iowa-1","make_s3_gamma_path": "gamma/tiffs"}}'}) for trigger "aws.sqs_new_message": '{"params": { "target": "dedacted","stack_id": "test-iowa-1","make_s3_gamma_path": "gamma/tiffs"}}' is not of type u'object', 'null'

Failed validating u'type' in schema[u'properties'][u'body']:
    {u'type': [u'object', 'null']}

```

Turns out someone forgot to turn the message body back into a `dict`.  This patch fixes the problem

### CODE REVIEW

**Comment by Kami** [comment]
Thank you for the contribution.

Is it guaranteed that ``body`` is always a JSON string? Or it can also be an arbitrary string, similar to the situation here - https://github.com/StackStorm-Exchange/stackstorm-kafka/pull/8.

**Comment by jegesh** [comment]
In the [sensor definition](https://github.com/StackStorm-Exchange/stackstorm-aws/blob/221a9cbc335618a3e3c4188ce09b59ca7f02fd89/sensors/sqs_sensor.yaml#L15) it expects an object (or null).  When I pass a string it raises an exception (see my first comment)

**Comment by LindsayHill** [comment]
Looks like tests might need updating, to fix these test [failures](https://circleci.com/gh/StackStorm-Exchange/stackstorm-aws/278?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

**Comment by jegesh** [comment]
@LindsayHill is someone on this, or is the expectation that I fix the tests as well? Sorry if the standard protocol is not clear to me

**Comment by LindsayHill** [comment]
Normally if you make a change that breaks tests, it is your responsibility to update those tests. 

No-one else is actively working on it, or has publicly said they plan to

**Comment by jegesh** [comment]
Can I get a merge, please?

**Review by arm4b — CHANGES_REQUESTED** [review]
Thanks for the fix!

Please include a Changelog in `CHANGES.md` and raise a pack version in `pack.yaml` so we can merge it.

**Review by arm4b — APPROVED** [review]

**Pull request merged**
