### PR TITLE
fixed types for ec2_create_tags, ec2_delete_tags, vpc_create_tags and vpc_delete_tags

### PR DESCRIPTION
**Pull request by minhnhdo**

### CODE REVIEW

**Comment by userlocalhost** [comment]
This looks good to me.

Here is the interface of `create_tags` method in boto (v2.41.0) on which aws-pack depends.
```
vagrant@ubuntu:~/boto$ git checkout -b 2.41.0 refs/tags/2.41.0
Switched to a new branch '2.41.0'
vagrant@ubuntu:~/boto$ git log | head
commit b5be4791f1c74173e663d6ebaef024a341f536c9
Merge: b915894 80109f0
Author: JordonPhillips <phjordon@amazon.com>
Date:   Mon Jun 27 18:01:15 2016 -0700

    Merge branch 'release-2.41.0'

commit 80109f038054845f7ca64a4027d6a1fc61dd7d36
Author: JordonPhillips <phjordon@amazon.com>
Date:   Mon Jun 27 18:00:20 2016 -0700
vagrant@ubuntu:~/boto$ grep -n -A 6 "def create_tags" boto/ec2/connection.py
4197:    def create_tags(self, resource_ids, tags, dry_run=False):
4198-        """
4199-        Create new metadata tags for the specified resource ids.
4200-
4201-        :type resource_ids: list
4202-        :param resource_ids: List of strings
4203-
vagrant@ubuntu:~/boto$ 
```

According to that, the type of `resource_ids` parameters might be `list`. So I think this correction is right.

**Comment by Kami** [comment]
Thanks for the contribution and thanks to @userlocalhost for confirming the fix.

The change also looks good to me, but it's also worth noting that this file was auto-generated so we need to make sure this change, if correct, is not overwritten next time the generator script is ran.

**Comment by Kami** [comment]
@mrordinaire It looks like there are other actions for managing tags (e.g. `ec2_delete_tags`) which also take `resource_ids` but the type is a string.

Do those actions also need to be updated?

**Comment by minhnhdo** [comment]
@Kami, can you please point me to where the code for auto-generation of these manifests is? I'll take a look at the code. In the mean time, I've added corrections for ec2_delete_tags, vpc_create_tags and vpc_delete_tags.

**Comment by Kami** [comment]
Thanks.

The code is here - https://github.com/StackStorm-Exchange/stackstorm-aws/tree/master/etc/st2packgen

**Comment by minhnhdo** [comment]
@userlocalhost thank you for the code review.

**Comment by minhnhdo** [comment]
@Kami, thanks for the prompt reply. I'll work on this later.

**Comment by Kami** [comment]
Thanks - will go ahead and merge this for now :)

**Comment by minhnhdo** [comment]
@Kami I just ran the script to generate the manifest again and it seems that the type of the arguments are correct but the argument names change.

I ran `python st2packgen.py --service ec2`. The generated content for `actions/ec2_create_tags.yml` follows
```
description: 
pack: aws
enabled: true
entry_point: run.py
name: ec2_create_tags
runner_type: run-python
parameters:
  action:
    default: create_tags
    immutable: true
    type: string
  cls:
    default: ec2
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Resources:
    type: array
    description: "The IDs of one or more resources to tag. For example, ami-1a2b3c4d."
    required: true
  Tags:
    type: array
    description: "One or more tags. The value parameter is required, but if you don't want the tag to have a value, specify the parameter with no value, and we set the value to an empty string. "
    required: true
  DryRun:
    type: boolean
    description: "Checks whether you have the required permissions for the action, without actually making the request, and provides an error response. If you have the required permissions, the error response is DryRunOperation. Otherwise, it is UnauthorizedOperation."
```

**Comment by Kami** [comment]
Thanks.

Yeah, IIRC it depends on the version of boto you use when you run the script...

**Pull request merged**
