### PR TITLE
Fix kwargs['user_data'] parameter to what boto expects

### PR DESCRIPTION
**Pull request by punkrokk**
Fix kwargs['user_data'] parameter to what boto expects

According to the boto3 docs, we need to pass in the parameter 'UserData', not "user_data" which is being passed in.

### CODE REVIEW

**Review by m4dcoder — CHANGES_REQUESTED** [review]
You will also need to rename user_data at https://github.com/StackStorm-Exchange/stackstorm-aws/blob/master/actions/run.py#L19.

```
if aws_action == 'run_instances' and not kwargs.get('UserData', None)
```

Also, please update references to user_data at README.md, increment the pack version, and also an entry in CHANGES.md

**Comment by m4dcoder** [comment]
Adding boto documentation reference here https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.run_instances.  Also, I checked that the ec2_run_instances action is populated correctly with the UserData input parameter.

**Comment by punkrokk** [comment]
@m4dcoder done :)

**Comment by punkrokk** [comment]
@m4dcoder: @LindsayHill recommended I get back to you now that my fixes are here.

**Comment by Kami** [comment]
Just a heads up- IIRC, we have some workflows in st2cd / st2cdi repo which rely on parameter being named ``user_data`` so if we update pack on our deployment we also need to update parameter name in the workflows.

**Comment by arm4b** [comment]
@Kami We rely on old/pinned version of `aws` pack so that should be OK.

**Comment by m4dcoder** [comment]
@Kami @armab I found reference in ops-infra where we pin the AWS pack to aws=v0.10.0-user-data-fix-patch.  The aws.ec2_run_instances in v0.10 is still using user_data and our st2cicd isn't going to be affected as @armab says. We will likely have to upgrade our reference to the AWS pack at some point.  In the current version 1.2.0 for the AWS pack, the input is already changed to UserData so this PR here is just going to fix what's broken.

**Review by m4dcoder — APPROVED** [review]
LGTM but wait for my colleague to approve as well.

**Comment by arm4b** [comment]
Merged, that was a good catch :+1:

**Pull request merged**
