### PR TITLE
Updated boto3, removed deprecated import path

### PR DESCRIPTION
**Pull request by LindsayHill**
Also cleaned up mixed up CHANGES.md vs CHANGES.rst that still existed on this branch.

This replaces #59

### CODE REVIEW

**Comment by LindsayHill** [comment]
_sigh_. More investigation into why tests are failing needed I guess.

**Comment by Susanthab** [comment]
@LindsayHill Just a quick question, how feasible to have boto3 pack with only just two actions which essential need to perform all aws activities?  Those two actions are;
1. aws.assume_role 
2. aws.boto3action 

So that users can have the choice to use either regular aws pack or this boto3 pack.

**Comment by LindsayHill** [comment]
@Susanthab probably better to ask broader questions via Slack or a new GH issue, rather than on this PR. You probably want to have a read through some of the other discussions around the AWS pack, and talk to people like @AndyMoore111 who are planning a new way of doing things. 

Possible starting point is here https://github.com/StackStorm-Exchange/exchange-incubator/pull/10, and the issues/PRs linked from there. e.g. "[Discussion on the future of the AWS pack](https://github.com/StackStorm-Exchange/stackstorm-aws/issues/55)"

**Comment by Susanthab** [comment]
thanks.  will do.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
