### PR TITLE
Corrected 'filters' parameter type of 'vpc_get_all_subnets' action

### PR DESCRIPTION
**Pull request by userlocalhost**
This is the correction of #11.

The reason of this program is the incorrect parameter type of 'filters'.

The [boto.vpc.VPCConnection.get_all_subnets](http://boto.cloudhackers.com/en/latest/ref/vpc.html#boto.vpc.VPCConnection.get_all_subnets) requires `filters` parameter requires 'list' of 'dict' type, but the 'aws.vpc_get_all_subnets' action requires 'string' type.

So I corrected the parameter type of it from 'string' to 'object'.

By this patch, user can use this action with `filters` parameter normally like this.
```
(virtualenv)vagrant@ubuntu2:~$ st2 action get aws.vpc_get_all_subnets
+-------------+----------------------------------------+
| Property    | Value                                  |
+-------------+----------------------------------------+
| id          | 5880676c88fa3f03a3fcc791               |
| uid         | action:aws:vpc_get_all_subnets         |
| ref         | aws.vpc_get_all_subnets                |
| pack        | aws                                    |
| name        | vpc_get_all_subnets                    |
| description |                                        |
| enabled     | True                                   |
| entry_point | run.py                                 |
| runner_type | run-python                             |
| parameters  | {                                      |
|             |     "dry_run": {                       |
|             |         "default": false,              |
|             |         "type": "boolean"              |
|             |     },                                 |
|             |     "filters": {                       |
|             |         "type": "object"               |
|             |     },                                 |
|             |     "action": {                        |
|             |         "default": "get_all_subnets",  |
|             |         "type": "string",              |
|             |         "immutable": true              |
|             |     },                                 |
|             |     "module_path": {                   |
|             |         "default": "boto.vpc",         |
|             |         "type": "string",              |
|             |         "immutable": true              |
|             |     },                                 |
|             |     "subnet_ids": {                    |
|             |         "type": "string"               |
|             |     },                                 |
|             |     "cls": {                           |
|             |         "default": "VPCConnection",    |
|             |         "type": "string",              |
|             |         "immutable": true              |
|             |     }                                  |
|             | }                                      |
| notify      |                                        |
| tags        |                                        |
+-------------+----------------------------------------+
(virtualenv)vagrant@ubuntu2:~$ st2 run aws.vpc_get_all_subnets filters='vpc_id=vpc-8e5aaceb'
..
id: 5880978388fa3f283f10d2ab
status: succeeded
parameters: 
  filters:
    vpc_id: vpc-8e5aaceb
result: 
  exit_code: 0
  result:
  - availability_zone: ap-northeast-1a
    available_ip_address_count: 251
    cidr_block: 172.30.0.0/24
    defaultForAz: 'false'
    id: subnet-aa08fedd
    item: "
        "
    mapPublicIpOnLaunch: 'true'
    region: ap-northeast-1
    state: available
    tags: {}
    vpc_id: vpc-8e5aaceb
  - availability_zone: ap-northeast-1c
    available_ip_address_count: 251
    cidr_block: 172.30.2.0/24
    defaultForAz: 'false'
    id: subnet-c8b8b28e
    item: "
        "
    mapPublicIpOnLaunch: 'true'
    region: ap-northeast-1
    state: available
    tags: {}
    vpc_id: vpc-8e5aaceb
  stderr: ''
  stdout: ''
(virtualenv)vagrant@ubuntu2:~$ 
```

### CODE REVIEW

**Comment by emedvedev** [comment]
Awesome! Mad props for the tests :heart:
Could you also bump the patch version in `pack.yaml`, please?

**Comment by userlocalhost** [comment]
You got it!

**Comment by userlocalhost** [comment]
Thank you for your comment.
I bumped the version number.

**Comment by emedvedev** [comment]
Merged. Thanks a lot!

**Pull request merged**
