### PR TITLE
Address problems with ec2 start and stop aliases

### PR DESCRIPTION
**Pull request by amanda11**
Update ec2 start and stop aliases to use InstanceIds parameter to match action, amend result handling and add unit-test.

Addresses: https://github.com/StackStorm-Exchange/stackstorm-aws/issues/98

### CODE REVIEW

**Review by nmaludy — CHANGES_REQUESTED** [review]
Looks good.

Can you please add a CHANGELOG entry and bump the pack version by 0.0.1 (bug fix)

**Comment by amanda11** [comment]
@nmaludy Will do. 

NB. To work on centos 8 then they also require the fix proprosed under issue #104 and the PR #103. But I've tested that if those are brought in they still work.

**Comment by amanda11** [comment]
@nmaludy I think I 've addressed your comments.

**Review by nmaludy — APPROVED** [review]
Thank  you very much for the contribution!

**Comment by nmaludy** [comment]
@amanda11 got this merged in, for #103 just need @jamison-rose to update the PR with a few changes. If you want, you could create your own PR with those same changes and potentially get it merged in sooner.

**Comment by amanda11** [comment]
@nmaludy Thanks. Happy to produce a PR with the other changes needed for python3, but will probably be next week until I get a chance. But I'll aim to get something up to close off those two python3 problems with the pack.

**Pull request merged**
