### PR TITLE
adding aliases

### PR DESCRIPTION
**Pull request by lshahar**

### CODE REVIEW

**Comment by LindsayHill** [comment]
The pack name in your aliases here doesn't match the overall pack name. Can you fix that so tests pass?

**Comment by lshahar** [comment]
I have fix the pack name, can you approve it please?

**Comment by LindsayHill** [comment]
Thanks for that fix. 

Can you also:
- Remove the .idea/stackstorm-aws.iml file from the PR
- increment pack.yaml & update CHANGES.md
- Remove the "GICI Global" footer, or change it, since it seems to be specific to your organization?

**Comment by lshahar** [comment]
fix all issue , but what is missing at  pack.yaml ?

**Comment by LindsayHill** [comment]
Just take the current `pack.yaml` file, and increment the version number, e.g. 0.9.2 -> 0.9.3

**Comment by lshahar** [comment]
Done

**Review by LindsayHill — APPROVED** [review]
I'm happy with the changes. @userlocalhost would you mind just double-checking? And then we can merge

**Review by userlocalhost — APPROVED** [review]
LGTM!

**Pull request merged**
